### ISSUE TITLE
Help setting it up

### ISSUE THREAD

**Issue by Myshiro** [WebBreacher/WhatsMyName#334] opened 2021-12-02 22:50 UTC
What’s the difference with the application and the website and I can’t set it up it doesn’t work

**Comment by WebBreacher** [comment] 2021-12-02 23:52
The https://whatsmyname.app site uses the same data file that the Python tools do you just get to use it in a web browser. 

Without details about what is not working, it is very challenging me to assist. Can you provide more details (or just focus on using the website and not the Python tools)?

**Comment by Myshiro** [comment] 2021-12-03 07:22
I want to know how to add websites to search in the code so more sites like epic games, psn, and a lot of others. Furthermore it says this error when i try torun python web_accounts_list_checker.py in cmd in the checkers folders location.

" C:\Users\_____\Desktop\WhatsMyName-master>python web_accounts_list_checker.py
Traceback (most recent call last):
  File "C:\Users\_____\Desktop\WhatsMyName-master\web_accounts_list_checker.py", line 174, in <module>
    data = json.load(data_file)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2544.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 2027: character maps to <undefined> "

**Comment by Myshiro** [comment] 2021-12-03 07:25
I have downloaded the

urllib3
selenium
selenium-wire

**Comment by WebBreacher** [comment] 2021-12-03 14:53
I'm wondering:
1. Before running the above command, did you alter the JSON file (`web_accounts_list.json`) and add your sites in there?
    1. If so, did the `web_accounts_list_checker.py` tool ever run correctly before you altered the JSON file?
    2. If it did, then the issue is in the JSON file changes.
        1. The JSON m,ay not be valid. Try copying the JSON and pasting it into a "checker" site like https://jsonchecker.com/ and see if it is valid or if you are missing some characters.
        2. It may be that you are using certain unicode characters that are causing the above issue. If so, sharing what you added to the JSON file would be helpful.
1. If you want to keep custom JSON site checking entries private, you are welcome to. But you may wish to add them to the project so others can benefit from the tools checking these addtional sites. If you'd like to do this, you can post your JSON or sites/URLs here and I can see about adding them.

Hoping this helps.

**Comment by Myshiro** [comment] 2021-12-05 01:49
I didn’t edit the file I don’t know how to edit it so I’m asking how do I add more sites so it works and also it doesn’t work even when I don’t add the custom sites, it says “duplicate key ‘account_missing_string’ on line 2064 when I traded it to json checker

**Comment by WebBreacher** [comment] 2021-12-05 03:00
Thanks for the info. If you did not edit the JSON file then it should be valid. I've just checked it (not in the JSONchecker site but https://codebeautify.org/jsonvalidator) and it is valid.

Can you show me exactly what you are typing to run the program? It should be something like `python3 web_accounts_list_checker.py -u username`. This will check the `username` value in the sites. 

To add your own sites to the file, you can copy the format of one of the sites within the JSON file. For example, if I wanted to add example.com to the end of the file, I would add

```
      },
      {
        "name" : "Example",
        "check_uri" : "https://example.com/user/{account}",
        "account_existence_code" : "200",
        "account_existence_string" : "String to detect",
        "account_missing_string" : "user not found string",
        "account_missing_code" : "404",
        "known_accounts" : ["testuser1","testuser2
        "category" : "social",
        "valid" : true
      }
```

Make sure that you change the closing `}` in the final entry of the JSON file from just the `}` to `},` (adding a comma). 

Once you have that, you can run the command to just check that site (`python3 web_accounts_list_checker.py -u username -s example`) or to check that username in all sites (`python3 web_accounts_list_checker.py -u username`) 

Hoping this helps. Perhaps this week I'll make a tutorial video showing how to do this.

**Comment by Myshiro** [comment] 2021-12-05 03:27
Hi there, thanks for the quick response however
![6290CF8E-553B-4BED-95E6-ABC677AA34E9](https://user-images.githubusercontent.com/95185030/144732242-78f5a312-3752-411b-9b86-90e5a7d047ed.png)
 there is still an error

**Comment by WebBreacher** [comment] 2021-12-06 13:24
So... maybe we should start at the beginning. How did you download the WhatsMyName software to your computer?

Also, when did you download it?

**Comment by WebBreacher** [comment] 2021-12-06 13:58
i did a little more testing on a Windows system (since it appears that is what you are using) and was able to recreate your error. I've just pushed a fix to the `master` branch to fix this issue. Please do a `git pull` to retrieve the changed code.

**Comment by WebBreacher** [comment] 2021-12-14 13:04
Any feedback here @Myshiro ? If you `git pull` and then rerun the command does it work now?

**Comment by WebBreacher** [comment] 2022-04-10 20:33
Closing issue due to inactivity.

**Closed by WebBreacher** 2022-04-10 20:33 UTC
