### ISSUE TITLE
Recheck requirements.txt (cleo, clikit, crashtest)

### ISSUE THREAD

**Issue by JD777777777** [WebBreacher/WhatsMyName#668] opened 2023-01-20 22:32 UTC
I installed requirements.txt with pip a few hours ago.
For me it only worked after I deleted the version numbers for the packages cleo, clikit and crashtest.
Otherwise pip would throw me a "dependencies unresolvable" kind of error.

**Comment by WebBreacher** [comment] 2023-01-22 15:28
@yooper can you address/investigate this?

**Comment by yooper** [comment] 2023-01-22 15:43
@JD777777777 , what version of python are you using?

**Comment by JD777777777** [comment] 2023-01-22 21:12
>python --version
Python 3.11.1 (on Windows)

**Comment by yooper** [comment] 2023-01-30 10:36
Most likely the issue is you are using the latest and greatest version of python 3.11.1 and the specified packages didn't install because of compatibility issues. The code was developed against python 3.8, supporting other versions, isn't difficult per se, but does require more time, from volunteers.

**Comment by WebBreacher** [comment] 2023-02-21 15:33
@yooper I'm having same issue on Ubuntu 22.04.2 with Python 3.10.6 
![image](https://user-images.githubusercontent.com/2359093/220388779-27c813a9-9260-410e-bc0f-1ee06d92e2b8.png)

**Comment by WebBreacher** [comment] 2023-02-21 15:36
Until @yooper has time to address this, a temp fix is to remove the versions of clikit, cleo, and crashtest which I will do.

**Comment by WebBreacher** [comment] 2023-02-21 15:43
@JD777777777 can you confirm that this fixed your issues?

**Comment by WebBreacher** [comment] 2023-03-06 13:05
Fixed with #687

**Closed by WebBreacher** 2023-03-06 13:05 UTC
